'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.Win32
Imports Microsoft.Win32.SafeHandles
Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.IO
Imports System.Security.AccessControl
Imports System.Text


<GeneratedCode("0.0.0.1", "ArtisanCode.Grass")>  _
Public Interface IFile
    
    Sub AppendAllLines(ByVal path As String, ByVal contents As System.Collections.Generic.IEnumerable(Of String))
    
    Sub AppendAllLines(ByVal path As String, ByVal contents As System.Collections.Generic.IEnumerable(Of String), ByVal encoding As System.Text.Encoding)
    
    Sub AppendAllText(ByVal path As String, ByVal contents As String)
    
    Sub AppendAllText(ByVal path As String, ByVal contents As String, ByVal encoding As System.Text.Encoding)
    
    Function AppendText(ByVal path As String) As System.IO.StreamWriter
    
    Sub Copy(ByVal sourceFileName As String, ByVal destFileName As String)
    
    Sub Copy(ByVal sourceFileName As String, ByVal destFileName As String, ByVal overwrite As Boolean)
    
    Function Create(ByVal path As String) As System.IO.FileStream
    
    Function Create(ByVal path As String, ByVal bufferSize As Integer) As System.IO.FileStream
    
    Function Create(ByVal path As String, ByVal bufferSize As Integer, ByVal options As System.IO.FileOptions) As System.IO.FileStream
    
    Function Create(ByVal path As String, ByVal bufferSize As Integer, ByVal options As System.IO.FileOptions, ByVal fileSecurity As System.Security.AccessControl.FileSecurity) As System.IO.FileStream
    
    Function CreateText(ByVal path As String) As System.IO.StreamWriter
    
    Sub Decrypt(ByVal path As String)
    
    Sub Delete(ByVal path As String)
    
    Sub Encrypt(ByVal path As String)
    
    Function Exists(ByVal path As String) As Boolean
    
    Function GetAccessControl(ByVal path As String) As System.Security.AccessControl.FileSecurity
    
    Function GetAccessControl(ByVal path As String, ByVal includeSections As System.Security.AccessControl.AccessControlSections) As System.Security.AccessControl.FileSecurity
    
    Function GetAttributes(ByVal path As String) As System.IO.FileAttributes
    
    Function GetCreationTime(ByVal path As String) As Date
    
    Function GetCreationTimeUtc(ByVal path As String) As Date
    
    Function GetLastAccessTime(ByVal path As String) As Date
    
    Function GetLastAccessTimeUtc(ByVal path As String) As Date
    
    Function GetLastWriteTime(ByVal path As String) As Date
    
    Function GetLastWriteTimeUtc(ByVal path As String) As Date
    
    Sub Move(ByVal sourceFileName As String, ByVal destFileName As String)
    
    Function Open(ByVal path As String, ByVal mode As System.IO.FileMode) As System.IO.FileStream
    
    Function Open(ByVal path As String, ByVal mode As System.IO.FileMode, ByVal access As System.IO.FileAccess) As System.IO.FileStream
    
    Function Open(ByVal path As String, ByVal mode As System.IO.FileMode, ByVal access As System.IO.FileAccess, ByVal share As System.IO.FileShare) As System.IO.FileStream
    
    Function OpenRead(ByVal path As String) As System.IO.FileStream
    
    Function OpenText(ByVal path As String) As System.IO.StreamReader
    
    Function OpenWrite(ByVal path As String) As System.IO.FileStream
    
    Function ReadAllBytes(ByVal path As String) As Byte()
    
    Function ReadAllLines(ByVal path As String) As String()
    
    Function ReadAllLines(ByVal path As String, ByVal encoding As System.Text.Encoding) As String()
    
    Function ReadAllText(ByVal path As String) As String
    
    Function ReadAllText(ByVal path As String, ByVal encoding As System.Text.Encoding) As String
    
    Function ReadLines(ByVal path As String) As System.Collections.Generic.IEnumerable(Of String)
    
    Function ReadLines(ByVal path As String, ByVal encoding As System.Text.Encoding) As System.Collections.Generic.IEnumerable(Of String)
    
    Sub Replace(ByVal sourceFileName As String, ByVal destinationFileName As String, ByVal destinationBackupFileName As String)
    
    Sub Replace(ByVal sourceFileName As String, ByVal destinationFileName As String, ByVal destinationBackupFileName As String, ByVal ignoreMetadataErrors As Boolean)
    
    Sub SetAccessControl(ByVal path As String, ByVal fileSecurity As System.Security.AccessControl.FileSecurity)
    
    Sub SetAttributes(ByVal path As String, ByVal fileAttributes As System.IO.FileAttributes)
    
    Sub SetCreationTime(ByVal path As String, ByVal creationTime As Date)
    
    Sub SetCreationTimeUtc(ByVal path As String, ByVal creationTimeUtc As Date)
    
    Sub SetLastAccessTime(ByVal path As String, ByVal lastAccessTime As Date)
    
    Sub SetLastAccessTimeUtc(ByVal path As String, ByVal lastAccessTimeUtc As Date)
    
    Sub SetLastWriteTime(ByVal path As String, ByVal lastWriteTime As Date)
    
    Sub SetLastWriteTimeUtc(ByVal path As String, ByVal lastWriteTimeUtc As Date)
    
    Sub WriteAllBytes(ByVal path As String, ByVal bytes() As Byte)
    
    Sub WriteAllLines(ByVal path As String, ByVal contents() As String)
    
    Sub WriteAllLines(ByVal path As String, ByVal contents() As String, ByVal encoding As System.Text.Encoding)
    
    Sub WriteAllLines(ByVal path As String, ByVal contents As System.Collections.Generic.IEnumerable(Of String))
    
    Sub WriteAllLines(ByVal path As String, contents As System.Collections.Generic.IEnumerable(Of String), encoding As System.Text.Encoding)
    
    Sub WriteAllText(ByVal path As String, ByVal contents As String)
    
    Sub WriteAllText(ByVal path As String, ByVal contents As String, ByVal encoding As System.Text.Encoding)
End Interface
