'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.Win32
Imports Microsoft.Win32.SafeHandles
Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.IO
Imports System.Security.AccessControl
Imports System.Text


<GeneratedCode("0.0.0.1", "ArtisanCode.Grass")>  _
Partial Public Class FileWrapper
    Inherits Object
    Implements IFile
    
    Public Overloads Overridable Sub AppendAllLines(ByVal path As String, ByVal contents As System.Collections.Generic.IEnumerable(Of String)) Implements IFile.AppendAllLines
        File.AppendAllLines(path, contents)
    End Sub
    
    Public Overloads Overridable Sub AppendAllLines(ByVal path As String, ByVal contents As System.Collections.Generic.IEnumerable(Of String), ByVal encoding As System.Text.Encoding) Implements IFile.AppendAllLines
        File.AppendAllLines(path, contents, encoding)
    End Sub
    
    Public Overloads Overridable Sub AppendAllText(ByVal path As String, ByVal contents As String) Implements IFile.AppendAllText
        File.AppendAllText(path, contents)
    End Sub
    
    Public Overloads Overridable Sub AppendAllText(ByVal path As String, ByVal contents As String, ByVal encoding As System.Text.Encoding) Implements IFile.AppendAllText
        File.AppendAllText(path, contents, encoding)
    End Sub
    
    Public Overridable Function AppendText(ByVal path As String) As System.IO.StreamWriter Implements IFile.AppendText
        Return File.AppendText(path)
    End Function
    
    Public Overloads Overridable Sub Copy(ByVal sourceFileName As String, ByVal destFileName As String) Implements IFile.Copy
        File.Copy(sourceFileName, destFileName)
    End Sub
    
    Public Overloads Overridable Sub Copy(ByVal sourceFileName As String, ByVal destFileName As String, ByVal overwrite As Boolean) Implements IFile.Copy
        File.Copy(sourceFileName, destFileName, overwrite)
    End Sub
    
    Public Overloads Overridable Function Create(ByVal path As String) As System.IO.FileStream Implements IFile.Create
        Return File.Create(path)
    End Function
    
    Public Overloads Overridable Function Create(ByVal path As String, ByVal bufferSize As Integer) As System.IO.FileStream Implements IFile.Create
        Return File.Create(path, bufferSize)
    End Function
    
    Public Overloads Overridable Function Create(ByVal path As String, ByVal bufferSize As Integer, ByVal options As System.IO.FileOptions) As System.IO.FileStream Implements IFile.Create
        Return File.Create(path, bufferSize, options)
    End Function
    
    Public Overloads Overridable Function Create(ByVal path As String, ByVal bufferSize As Integer, ByVal options As System.IO.FileOptions, ByVal fileSecurity As System.Security.AccessControl.FileSecurity) As System.IO.FileStream Implements IFile.Create
        Return File.Create(path, bufferSize, options, fileSecurity)
    End Function
    
    Public Overridable Function CreateText(ByVal path As String) As System.IO.StreamWriter Implements IFile.CreateText
        Return File.CreateText(path)
    End Function
    
    Public Overridable Sub Decrypt(ByVal path As String) Implements IFile.Decrypt
        File.Decrypt(path)
    End Sub
    
    Public Overridable Sub Delete(ByVal path As String) Implements IFile.Delete
        File.Delete(path)
    End Sub
    
    Public Overridable Sub Encrypt(ByVal path As String) Implements IFile.Encrypt
        File.Encrypt(path)
    End Sub
    
    Public Overridable Function Exists(ByVal path As String) As Boolean Implements IFile.Exists
        Return File.Exists(path)
    End Function
    
    Public Overloads Overridable Function GetAccessControl(ByVal path As String) As System.Security.AccessControl.FileSecurity Implements IFile.GetAccessControl
        Return File.GetAccessControl(path)
    End Function
    
    Public Overloads Overridable Function GetAccessControl(ByVal path As String, ByVal includeSections As System.Security.AccessControl.AccessControlSections) As System.Security.AccessControl.FileSecurity Implements IFile.GetAccessControl
        Return File.GetAccessControl(path, includeSections)
    End Function
    
    Public Overridable Function GetAttributes(ByVal path As String) As System.IO.FileAttributes Implements IFile.GetAttributes
        Return File.GetAttributes(path)
    End Function
    
    Public Overridable Function GetCreationTime(ByVal path As String) As Date Implements IFile.GetCreationTime
        Return File.GetCreationTime(path)
    End Function
    
    Public Overridable Function GetCreationTimeUtc(ByVal path As String) As Date Implements IFile.GetCreationTimeUtc
        Return File.GetCreationTimeUtc(path)
    End Function
    
    Public Overridable Function GetLastAccessTime(ByVal path As String) As Date Implements IFile.GetLastAccessTime
        Return File.GetLastAccessTime(path)
    End Function
    
    Public Overridable Function GetLastAccessTimeUtc(ByVal path As String) As Date Implements IFile.GetLastAccessTimeUtc
        Return File.GetLastAccessTimeUtc(path)
    End Function
    
    Public Overridable Function GetLastWriteTime(ByVal path As String) As Date Implements IFile.GetLastWriteTime
        Return File.GetLastWriteTime(path)
    End Function
    
    Public Overridable Function GetLastWriteTimeUtc(ByVal path As String) As Date Implements IFile.GetLastWriteTimeUtc
        Return File.GetLastWriteTimeUtc(path)
    End Function
    
    Public Overridable Sub Move(ByVal sourceFileName As String, ByVal destFileName As String) Implements IFile.Move
        File.Move(sourceFileName, destFileName)
    End Sub
    
    Public Overloads Overridable Function Open(ByVal path As String, ByVal mode As System.IO.FileMode) As System.IO.FileStream Implements IFile.Open
        Return File.Open(path, mode)
    End Function
    
    Public Overloads Overridable Function Open(ByVal path As String, ByVal mode As System.IO.FileMode, ByVal access As System.IO.FileAccess) As System.IO.FileStream Implements IFile.Open
        Return File.Open(path, mode, access)
    End Function
    
    Public Overloads Overridable Function Open(ByVal path As String, ByVal mode As System.IO.FileMode, ByVal access As System.IO.FileAccess, ByVal share As System.IO.FileShare) As System.IO.FileStream Implements IFile.Open
        Return File.Open(path, mode, access, share)
    End Function
    
    Public Overridable Function OpenRead(ByVal path As String) As System.IO.FileStream Implements IFile.OpenRead
        Return File.OpenRead(path)
    End Function
    
    Public Overridable Function OpenText(ByVal path As String) As System.IO.StreamReader Implements IFile.OpenText
        Return File.OpenText(path)
    End Function
    
    Public Overridable Function OpenWrite(ByVal path As String) As System.IO.FileStream Implements IFile.OpenWrite
        Return File.OpenWrite(path)
    End Function
    
    Public Overridable Function ReadAllBytes(ByVal path As String) As Byte() Implements IFile.ReadAllBytes
        Return File.ReadAllBytes(path)
    End Function
    
    Public Overloads Overridable Function ReadAllLines(ByVal path As String) As String() Implements IFile.ReadAllLines
        Return File.ReadAllLines(path)
    End Function
    
    Public Overloads Overridable Function ReadAllLines(ByVal path As String, ByVal encoding As System.Text.Encoding) As String() Implements IFile.ReadAllLines
        Return File.ReadAllLines(path, encoding)
    End Function
    
    Public Overloads Overridable Function ReadAllText(ByVal path As String) As String Implements IFile.ReadAllText
        Return File.ReadAllText(path)
    End Function
    
    Public Overloads Overridable Function ReadAllText(ByVal path As String, ByVal encoding As System.Text.Encoding) As String Implements IFile.ReadAllText
        Return File.ReadAllText(path, encoding)
    End Function
    
    Public Overloads Overridable Function ReadLines(ByVal path As String) As System.Collections.Generic.IEnumerable(Of String) Implements IFile.ReadLines
        Return File.ReadLines(path)
    End Function
    
    Public Overloads Overridable Function ReadLines(ByVal path As String, ByVal encoding As System.Text.Encoding) As System.Collections.Generic.IEnumerable(Of String) Implements IFile.ReadLines
        Return File.ReadLines(path, encoding)
    End Function
    
    Public Overloads Overridable Sub Replace(ByVal sourceFileName As String, ByVal destinationFileName As String, ByVal destinationBackupFileName As String) Implements IFile.Replace
        File.Replace(sourceFileName, destinationFileName, destinationBackupFileName)
    End Sub
    
    Public Overloads Overridable Sub Replace(ByVal sourceFileName As String, ByVal destinationFileName As String, ByVal destinationBackupFileName As String, ByVal ignoreMetadataErrors As Boolean) Implements IFile.Replace
        File.Replace(sourceFileName, destinationFileName, destinationBackupFileName, ignoreMetadataErrors)
    End Sub
    
    Public Overridable Sub SetAccessControl(ByVal path As String, ByVal fileSecurity As System.Security.AccessControl.FileSecurity) Implements IFile.SetAccessControl
        File.SetAccessControl(path, fileSecurity)
    End Sub
    
    Public Overridable Sub SetAttributes(ByVal path As String, ByVal fileAttributes As System.IO.FileAttributes) Implements IFile.SetAttributes
        File.SetAttributes(path, fileAttributes)
    End Sub
    
    Public Overridable Sub SetCreationTime(ByVal path As String, ByVal creationTime As Date) Implements IFile.SetCreationTime
        File.SetCreationTime(path, creationTime)
    End Sub
    
    Public Overridable Sub SetCreationTimeUtc(ByVal path As String, ByVal creationTimeUtc As Date) Implements IFile.SetCreationTimeUtc
        File.SetCreationTimeUtc(path, creationTimeUtc)
    End Sub
    
    Public Overridable Sub SetLastAccessTime(ByVal path As String, ByVal lastAccessTime As Date) Implements IFile.SetLastAccessTime
        File.SetLastAccessTime(path, lastAccessTime)
    End Sub
    
    Public Overridable Sub SetLastAccessTimeUtc(ByVal path As String, ByVal lastAccessTimeUtc As Date) Implements IFile.SetLastAccessTimeUtc
        File.SetLastAccessTimeUtc(path, lastAccessTimeUtc)
    End Sub
    
    Public Overridable Sub SetLastWriteTime(ByVal path As String, ByVal lastWriteTime As Date) Implements IFile.SetLastWriteTime
        File.SetLastWriteTime(path, lastWriteTime)
    End Sub
    
    Public Overridable Sub SetLastWriteTimeUtc(ByVal path As String, ByVal lastWriteTimeUtc As Date) Implements IFile.SetLastWriteTimeUtc
        File.SetLastWriteTimeUtc(path, lastWriteTimeUtc)
    End Sub
    
    Public Overridable Sub WriteAllBytes(ByVal path As String, ByVal bytes() As Byte) Implements IFile.WriteAllBytes
        File.WriteAllBytes(path, bytes)
    End Sub
    
    Public Overloads Overridable Sub WriteAllLines(ByVal path As String, ByVal contents() As String) Implements IFile.WriteAllLines
        File.WriteAllLines(path, contents)
    End Sub
    
    Public Overloads Overridable Sub WriteAllLines(ByVal path As String, ByVal contents() As String, ByVal encoding As System.Text.Encoding) Implements IFile.WriteAllLines
        File.WriteAllLines(path, contents, encoding)
    End Sub
    
    Public Overloads Overridable Sub WriteAllLines(ByVal path As String, ByVal contents As System.Collections.Generic.IEnumerable(Of String)) Implements IFile.WriteAllLines
        File.WriteAllLines(path, contents)
    End Sub
    
    Public Overloads Overridable Sub WriteAllLines(ByVal path As String, ByVal contents As System.Collections.Generic.IEnumerable(Of String), ByVal encoding As System.Text.Encoding) Implements IFile.WriteAllLines
        File.WriteAllLines(path, contents, encoding)
    End Sub
    
    Public Overloads Overridable Sub WriteAllText(ByVal path As String, ByVal contents As String) Implements IFile.WriteAllText
        File.WriteAllText(path, contents)
    End Sub
    
    Public Overloads Overridable Sub WriteAllText(ByVal path As String, ByVal contents As String, ByVal encoding As System.Text.Encoding) Implements IFile.WriteAllText
        File.WriteAllText(path, contents, encoding)
    End Sub
End Class
