//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtisanCode.UsingGrass.SubNamespace
{
    using System;
    using System.CodeDom.Compiler;
    using System.IO;
    using System.Text;
    
    
    [GeneratedCode("0.0.0.1", "ArtisanCode.Grass")]
    public interface IPath
    {
        
        string ChangeExtension(string path, string extension);
        
        string Combine(string path1, string path2);
        
        string Combine(string path1, string path2, string path3);
        
        string Combine(string path1, string path2, string path3, string path4);
        
        string Combine(string[] paths);
        
        string GetDirectoryName(string path);
        
        string GetExtension(string path);
        
        string GetFileName(string path);
        
        string GetFileNameWithoutExtension(string path);
        
        string GetFullPath(string path);
        
        char[] GetInvalidFileNameChars();
        
        char[] GetInvalidPathChars();
        
        string GetPathRoot(string path);
        
        string GetRandomFileName();
        
        string GetTempFileName();
        
        string GetTempPath();
        
        bool HasExtension(string path);
        
        bool IsPathRooted(string path);
    }
}
